FilmyProjekt/FilmyProjekt/filmy/urls.py
from django.urls import path
from filmy import views


app_name = 'filmy'

urlpatterns = [
    path('seznam/', views.seznam, name='seznam'),
    path('seznam/json/', views.seznam_json, name='seznam_json'),
    path('detail/<slug:slug>/', views.detail, name='detail'),

    path('seznam/hercu/', views.seznam_hercu, name='seznam_hercu'),
    path('detail-herce/<slug:slug>/', views.detail_herce, name='detail_herce'),
]



FilmyProjekt/FilmyProjekt/filmy/models.py
from django.db import models

# Create your models here.

FilmyProjekt/FilmyProjekt/filmy/views.py

from django.shortcuts import render, HttpResponse, Http404
from django.http import JsonResponse
from django.shortcuts import reverse
from django.utils.text import slugify
from filmy.data import filmy_data
from filmy.data_herci import herci_data


# Create your views here.
def seznam(request):
    slug = slugify(request.GET.get('text', ''))

    if slug:
        data = {}
        for key_film in filmy_data:
            if key_film.startswith(slug):
                data[key_film] = filmy_data[key_film]


        context = {'filmy_data': data}
    else:
        context = {'filmy_data': filmy_data}

    return render(request, 'filmy/seznam.html', context=context)

def detail(request, slug):
    if slug in filmy_data:
        film = filmy_data[slug]
        response = render(request, 'filmy/detail.html', context={'film': film})
        response['MOJE-DATA'] = 'HELLO'
        #response['Content-Type'] = 'application/json; charset=utf-8'
        return response
    else:
        raise Http404('Film nebyl nalezen')

def seznam_json(request):
    return JsonResponse(filmy_data)

def seznam_hercu(request):
    return render(request, 'filmy/seznam_herci.html', context={'herci': herci_data})

def detail_herce(request, slug):
    if slug in herci_data:
        herec = herci_data[slug]
        return render(request, 'filmy/detail_herci.html', context={'herec' : herec})
    else:
        raise Http404 ("Herec nebyl nalezen")



"""
0) mít data v dict
1) views.py
seznam_hercu -> return render() + html
detail_herce -> return render() + html

2) urls.py
/seznam_herci/
-> /filmy/seznam-hercu/

/detail-herce/<slug:slug>/
-> /filmy/detail-herce/jim_carrey/


3) nedělat search
"""

FilmyProjekt/FilmyProjekt/filmy/templates/filmy/detail.html
<!doctype html>{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@1/css/pico.min.css">
    <link rel="stylesheet" href="{% static 'filmy/style2.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<main class="container">
    <nav>
        <ul>
            <li>
                <a href="{% url 'filmy:seznam' %}">Seznam filmů</a>
            </li>
        </ul>
    </nav>

    {% include 'filmy/search_form.html' %}

    <h1>{{ film.nazev }}</h1>
    <p>{{ film.popis }}</p>

    <ul>

        {% for slug, jmeno in film.herci.items %}
        <li>
            <a href="{% url 'filmy:detail_herce' slug=slug %}">{{ jmeno }}</a>
        </li>
        {% endfor %}


    </ul>



</main>

</body>
</html>

FilmyProjekt/FilmyProjekt/filmy/templates/filmy/detail_herci.html
<!doctype html>{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@1/css/pico.min.css">
    <link rel="stylesheet" href="{% static 'filmy/style2.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<main class="container">
    <nav>
        <ul>
            <li>
                <a href="{% url 'filmy:seznam_hercu' %}">Seznam herců</a>
            </li>
        </ul>
    </nav>



    <h1>{{ herec.nazev }}</h1>
    <p>{{ herec.popis }}</p>
</main>

</body>
</html>

FilmyProjekt/FilmyProjekt/filmy/templates/filmy/search_form.html
 <form method="GET" action="{% url  'filmy:seznam' %}">
     <input type="search" name="text" value="{{ request.GET.text }}"
        autocomplete=off
        spellcheck="false"
        minlength="0"
        autofocus>
 </form>

FilmyProjekt/FilmyProjekt/filmy/templates/filmy/seznam.html
<!doctype html>{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@1/css/pico.min.css">
     <link rel="stylesheet" href="{% static 'filmy/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<main class="container">
    <h1>SEZNAM</h1>


    {% include 'filmy/search_form.html' %}


    <ul>

        {% for slug, data in filmy_data.items %}
        <li>
            <a href="{% url 'filmy:detail' slug=slug %}">{{ data.nazev }}</a>
        </li>

        {% endfor %}

    </ul>

</main>



</body>
</html>

FilmyProjekt/FilmyProjekt/filmy/templates/filmy/seznam_herci.html
<!doctype html>{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SEZNAM HERCŮ - Filmy.com</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@1/css/pico.min.css">
    <link rel="stylesheet" href="{% static 'filmy/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<main class="container">
    <h1>SEZNAM HERCŮ</h1>

    <ul>

        {% for slug, data in herci.items %}

        <li>
            <a href="{% url 'filmy:detail_herce' slug=slug %}">{{ data.nazev }}</a>
        </li>

        {% endfor %}

    </ul>

</main>



</body>
</html>