EShop_project/_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls), # -> /admin/...
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('eshop.urls', namespace='eshop')), # /...
]

EShop_project/eshop/urls.py
from django.urls import path
from eshop import views

app_name = 'eshop'

urlpatterns = [
    path('', views.index, name='index'),
    path('kategorie/', views.kategorie_list, name='kategorie'),
    path('produkty/', views.produkt_list, name='produkt_list'),
    path('<slug:slug>/', views.kategorie_detail, name='kategorie_detail'),
    path('znacka/<slug:slug>/', views.znacka_detail, name='znacka_detail'),
    path('p/<slug:slug>/<int:pk>/', views.produkt_detail, name='produkt_detail'),
]

EShop_project/eshop/models.py
from django.db import models
from django.utils.text import slugify
from django.shortcuts import reverse


class SlugNazevModel(models.Model):
    nazev = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, blank=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.nazev

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.nazev)
        super().save(*args, **kwargs)


class Kategorie(SlugNazevModel):
    nadkategorie = models.ForeignKey(
        'self',
        on_delete=models.PROTECT,
        blank=True,
        null=True,
        related_name='podkategorie',
    )

    def get_absolute_url(self):
        return reverse('eshop:kategorie_detail', kwargs={'slug': self.slug})


class Znacka(SlugNazevModel):
    logo = models.ImageField(blank=True)

    def get_absolute_url(self):
        return reverse('eshop:znacka_detail', kwargs={'slug': self.slug})


class Produkt(SlugNazevModel):
    popis = models.TextField(max_length=1000, blank=True)
    aktualni_cena = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        blank=True,
        null=True,
    )
    znacka = models.ForeignKey(
        Znacka,
        on_delete=models.PROTECT,
        blank=True,
        null=True
    )
    kategorie = models.ManyToManyField(Kategorie, blank=True)
    mnozstvi = models.PositiveIntegerField(default=0)
    vlastnosti = models.JSONField(default=dict, blank=True)

    def get_absolute_url(self):
        return reverse('eshop:produkt_detail', kwargs={'slug': self.slug, 'pk': self.pk})


class Cena(models.Model):
    produkt = models.ForeignKey(Produkt, on_delete=models.PROTECT)
    hodnota = models.DecimalField(max_digits=10, decimal_places=2)
    plati_od = models.DateField()
    plati_do = models.DateField()

EShop_project/eshop/views.py
from django.shortcuts import render
from eshop.models import Kategorie, Produkt, Znacka


def index(request):
    kategorie = Kategorie.objects.all()
    return render(request, 'eshop/index.html', context={'kategorie': kategorie})


def kategorie_list(request):
    object_list = Kategorie.objects.all()
    return render(request, 'eshop/kategorie.html', context={'object_list': object_list})


def kategorie_detail(request, slug):
    kategorie = Kategorie.objects.get(slug=slug)
    return render(request, 'eshop/kategorie_detail.html', context={'kategorie': kategorie})


def znacka_detail(request, slug):
    znacka = Znacka.objects.get(slug=slug)
    produkty = Produkt.objects.filter(znacka=znacka)
    return render(request, 'eshop/znacka.html', context={'znacka': znacka, 'produkty': produkty})


def produkt_detail(request, slug, pk):
    produkt = Produkt.objects.get(slug=slug, pk=pk)
    return render(request, 'eshop/produkt.html', context={'produkt': produkt})


def produkt_list(request):
    object_list = Produkt.objects.all()
    return render(request, 'eshop/produkt_list.html', context={'object_list': object_list})

EShop_project/eshop/templates/eshop/_layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>E-SHOP</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
</head>
<body>

{% include 'eshop/include/nav.html' %}

<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column is-narrow"><!-- Boční panel -->

                <aside class="menu">
                    <p class="menu-label">Kategorie</p>
                    <ul class="menu-list">
                        {% for KAT in KATEGORIE %}
                            {% if not KAT.nadkategorie %}
                                <li>
                                    <a {% if KAT == kategorie %}class="is-active"{% endif %} href="{{ KAT.get_absolute_url }}">{{ KAT.nazev }}</a>
                                    <ul>
                                        {% for PODKAT in KAT.podkategorie.all %}
                                            <li><a {% if PODKAT == kategorie %}class="is-active"{% endif %} href="{{ PODKAT.get_absolute_url }}">{{ PODKAT.nazev }}</a></li>
                                        {% endfor %}
                                    </ul>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>

                    <p class="menu-label">Značky</p>
                    <ul class="menu-list">
                        {% for ZNACKA in ZNACKY %}
                            <li><a href="{{ ZNACKA.get_absolute_url }}">{{ ZNACKA.nazev }}</a></li>
                        {% endfor %}
                    </ul>
                </aside>

            </div><!-- END Boční panel -->
            <div class="column">
                {% block eshop_content %}
                {% endblock %}
            </div>
        </div>
    </div>
</section>
</body>
</html>

EShop_project/eshop/templates/eshop/include/nav.html
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="{% url 'eshop:index' %}">
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    </a>

    <a href="{% url 'eshop:kategorie' %}" class="navbar-item">Kategorie</a>
    <a href="{% url 'eshop:produkt_list' %}" class="navbar-item">Produkty</a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item">Link 1</a>
    </div>

    <div class="navbar-end">
      <a class="navbar-item">Link 4</a>
      <a class="navbar-item">Link 5</a>
      <a class="navbar-item">Link 6</a>
    </div>
  </div>
</nav>

EShop_project/eshop/templates/eshop/index.html
{% extends 'eshop/_layout.html' %}

{% block eshop_content %}
    <h1 class="title">INDEX</h1>


    {% for kat in kategorie %}
    <div>{{ kat }}</div>
    {% endfor  %}
{% endblock %}

EShop_project/eshop/templates/eshop/kategorie.html
{% extends 'eshop/_layout.html' %}

{% block eshop_content %}
<h1 title="Kategorie">Kategorie</h1>

<aside class="menu">
    <p class="menu-label">Kategorie</p>
    <ul class="-menu-list">
        {% for item in object_list %}
        <li>
            <a href="{{ item.get_absolute_url }}">{{ item.nazev }}</a>
        </li>
        {% endfor %}
    </ul>
</aside>

{% endblock %}

EShop_project/eshop/templates/eshop/kategorie_detail.html
{% extends 'eshop/_layout.html' %}

{% block eshop_content %}
    <h1 class="title">{{ kategorie.nazev }}</h1>
{% endblock %}

EShop_project/eshop/templates/eshop/produkt.html
{% extends 'eshop/_layout.html' %}

{% block eshop_content %}



<h1 class="title">{{ produkt.nazev }}</h1>
<div class="card">
    <div>
        <a href="#">{{ produkt.kategorie }}</a>
    </div>
    <div>
        <a href="#">{{ produkt.znacka.nazev }}</a>
    </div>
    <br>
    <p style="font-size:1.2em;">{{ produkt.popis }}</p>
    <br>
    <span style="font-size: 1.7em; text-align: left">Cena: {{ produkt.aktualni_cena }} Kč s DPH</span>
    <p>Na skladě: {{ produkt.mnozstvi }}</p>
    <br><br>
    <button class="button is-full is-warning">Přidat do košíku</button>
    <button class="button is-full is-primary">Koupit hned</button>


</div>

{% endblock %}

EShop_project/eshop/templates/eshop/produkt_list.html
{% extends 'eshop/_layout.html' %}

{% block eshop_content %}
    <h1 class="title">PRODUKT LIST</h1>

    <style>
        .column a img {
            transition: scale 0.2s;
        }

        .column a img:hover {
            opacity: 0.85;
            scale: 1.05;
        }
    </style>

    <div class="columns is-multiline">
        {% for produkt in object_list %}
            <div class="column is-4">
                <a href="{{ produkt.get_absolute_url }}">
                    <img src="https://picsum.photos/300/200?{{ forloop.counter }}" alt="">
                    <div>{{ produkt.nazev }}</div>
                </a>
            </div>
        {% endfor %}
    </div>

{% endblock %}

EShop_project/eshop/templates/eshop/znacka.html
{% extends 'eshop/_layout.html' %}

{% block eshop_content %}
    <h1 class="title">{{ znacka.nazev }}</h1>
    {% for produkt in produkty %}
    <a href="{{ produkt.get_absolute_url }}">
        <div>{{ produkt.nazev }}</div>
    </a>
    {% endfor  %}
{% endblock %}